import type {
  User,
  Workspace,
  Repository,
  Detection,
  Scan,
  Policy,
  ActivityEvent,
  Notification,
  MetricTrend,
  ClassificationBreakdown,
  RiskDistributionPoint,
  TrendAnnotation,
  MorningBrief,
  SecurityHealth,
  WorkQueueItem,
  AiRecommendation,
  BriefActivityItem,
  ConnectorSource,
  ConnectorActivity,
  DataSourcesRecommendation,
  HealthDistribution,
  RepositoryDetail,
  RepositoryHealthStatus,
} from '@/types';

export const organization: Workspace = {
  id: 'ws_acme',
  name: 'Acme Financial Services Ltd.',
  plan: 'Enterprise',
  region: 'eu-west-1',
};

export const workspaces: Workspace[] = [
  organization,
  { id: 'ws_acme_eu', name: 'Acme EU Subsidiary', plan: 'Business', region: 'eu-central-1' },
  { id: 'ws_acme_apac', name: 'Acme APAC Holdings', plan: 'Business', region: 'ap-southeast-1' },
];

export const currentUser: User = {
  id: 'u_sarah',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@acme-financial.com',
  role: 'Security Analyst',
  avatarColor: '#4F46E5',
  initials: 'SJ',
};

export const users: User[] = [
  currentUser,
  {
    id: 'u_michael',
    name: 'Michael Chen',
    email: 'michael.chen@acme-financial.com',
    role: 'CISO',
    avatarColor: '#0EA5E9',
    initials: 'MC',
  },
  {
    id: 'u_priya',
    name: 'Priya Nair',
    email: 'priya.nair@acme-financial.com',
    role: 'Compliance Officer',
    avatarColor: '#16A34A',
    initials: 'PN',
  },
  {
    id: 'u_david',
    name: 'David Miller',
    email: 'david.miller@acme-financial.com',
    role: 'IT Administrator',
    avatarColor: '#D97706',
    initials: 'DM',
  },
];

export const repositories: Repository[] = [
  {
    id: 'repo_sp_hr',
    name: 'SharePoint HR',
    type: 'sharepoint',
    environment: 'production',
    status: 'active',
    riskScore: 78,
    totalAssets: 48210,
    sensitiveAssets: 12480,
    lastScanned: '2026-07-29T08:14:00Z',
    owner: 'Priya Nair',
    region: 'eu-west-1',
  },
  {
    id: 'repo_sp_fin',
    name: 'SharePoint Finance',
    type: 'sharepoint',
    environment: 'production',
    status: 'scanning',
    riskScore: 91,
    totalAssets: 63740,
    sensitiveAssets: 28910,
    lastScanned: '2026-07-30T11:02:00Z',
    owner: 'Sarah Johnson',
    region: 'eu-west-1',
  },
  {
    id: 'repo_s3_eng',
    name: 'AWS S3 Engineering',
    type: 's3',
    environment: 'production',
    status: 'active',
    riskScore: 42,
    totalAssets: 124880,
    sensitiveAssets: 8740,
    lastScanned: '2026-07-28T03:41:00Z',
    owner: 'David Miller',
    region: 'us-east-1',
  },
  {
    id: 'repo_sf_an',
    name: 'Snowflake Analytics',
    type: 'snowflake',
    environment: 'production',
    status: 'active',
    riskScore: 64,
    totalAssets: 31200,
    sensitiveAssets: 15630,
    lastScanned: '2026-07-29T19:22:00Z',
    owner: 'Michael Chen',
    region: 'us-east-1',
  },
  {
    id: 'repo_pg_crm',
    name: 'PostgreSQL CRM',
    type: 'postgresql',
    environment: 'production',
    status: 'active',
    riskScore: 55,
    totalAssets: 18760,
    sensitiveAssets: 9420,
    lastScanned: '2026-07-29T14:08:00Z',
    owner: 'David Miller',
    region: 'eu-west-1',
  },
  {
    id: 'repo_ex_mail',
    name: 'Microsoft Exchange',
    type: 'exchange',
    environment: 'production',
    status: 'paused',
    riskScore: 70,
    totalAssets: 210400,
    sensitiveAssets: 64210,
    lastScanned: '2026-07-27T06:55:00Z',
    owner: 'Sarah Johnson',
    region: 'eu-west-1',
  },
  {
    id: 'repo_az_legal',
    name: 'Azure Blob Legal',
    type: 'azure-blob',
    environment: 'production',
    status: 'active',
    riskScore: 85,
    totalAssets: 42100,
    sensitiveAssets: 21900,
    lastScanned: '2026-07-29T22:17:00Z',
    owner: 'Priya Nair',
    region: 'eu-west-1',
  },
  {
    id: 'repo_gd_mktg',
    name: 'Google Drive Marketing',
    type: 'google-drive',
    environment: 'production',
    status: 'active',
    riskScore: 33,
    totalAssets: 38900,
    sensitiveAssets: 2140,
    lastScanned: '2026-07-28T16:30:00Z',
    owner: 'David Miller',
    region: 'us-east-1',
  },
];

export const detections: Detection[] = [
  {
    id: 'DTN-2041',
    title: 'Unencrypted PII detected in customer records export',
    severity: 'critical',
    status: 'investigating',
    repositoryId: 'repo_sp_fin',
    repositoryName: 'SharePoint Finance',
    classification: 'PII — Financial',
    detectedAt: '2026-07-30T09:42:00Z',
    affectedAssets: 1840,
    assignedTo: 'Sarah Johnson',
    description:
      'A bulk export of customer financial records was stored without envelope encryption, exposing 1,840 records containing account numbers and transaction history.',
  },
  {
    id: 'DTN-2040',
    title: 'Over-permissive access on Legal hold container',
    severity: 'high',
    status: 'open',
    repositoryId: 'repo_az_legal',
    repositoryName: 'Azure Blob Legal',
    classification: 'Privileged — Legal',
    detectedAt: '2026-07-30T07:15:00Z',
    affectedAssets: 320,
    assignedTo: 'Priya Nair',
    description:
      'A shared access signature grant provides read/write to the entire legal-hold container for 14 service principals outside the legal team.',
  },
  {
    id: 'DTN-2039',
    title: 'SSN pattern found in unstructured HR documents',
    severity: 'high',
    status: 'in_review',
    repositoryId: 'repo_sp_hr',
    repositoryName: 'SharePoint HR',
    classification: 'PII — Identity',
    detectedAt: '2026-07-29T22:04:00Z',
    affectedAssets: 612,
    assignedTo: 'Sarah Johnson',
    description:
      '612 onboarding documents contain unstructured Social Security Numbers stored outside the encrypted HR vault, violating the Identity Data policy.',
  },
  {
    id: 'DTN-2038',
    title: 'Public S3 bucket exposes engineering build artifacts',
    severity: 'medium',
    status: 'open',
    repositoryId: 'repo_s3_eng',
    repositoryName: 'AWS S3 Engineering',
    classification: 'Confidential — Source',
    detectedAt: '2026-07-29T18:50:00Z',
    affectedAssets: 54,
    assignedTo: 'David Miller',
    description:
      'An engineering release bucket was misconfigured with public read access, exposing 54 internal build artifacts and metadata manifests.',
  },
  {
    id: 'DTN-2037',
    title: 'Stale credentials in CRM connection string',
    severity: 'medium',
    status: 'remediated',
    repositoryId: 'repo_pg_crm',
    repositoryName: 'PostgreSQL CRM',
    classification: 'Credential — Secret',
    detectedAt: '2026-07-29T13:22:00Z',
    affectedAssets: 8,
    assignedTo: 'David Miller',
    description:
      'A deprecated database connection string containing embedded credentials was found in a configuration table. Rotated and invalidated.',
  },
  {
    id: 'DTN-2036',
    title: 'Analytics view leaks customer identifiers',
    severity: 'low',
    status: 'open',
    repositoryId: 'repo_sf_an',
    repositoryName: 'Snowflake Analytics',
    classification: 'PII — Identity',
    detectedAt: '2026-07-29T11:08:00Z',
    affectedAssets: 12400,
    assignedTo: 'Michael Chen',
    description:
      'A shared analytics view joins raw customer identifiers into a reporting schema accessible to the marketing analyst role.',
  },
  {
    id: 'DTN-2035',
    title: 'Marketing drive contains vendor pricing sheets',
    severity: 'low',
    status: 'closed',
    repositoryId: 'repo_gd_mktg',
    repositoryName: 'Google Drive Marketing',
    classification: 'Confidential — Commercial',
    detectedAt: '2026-07-28T15:40:00Z',
    affectedAssets: 23,
    assignedTo: 'David Miller',
    description:
      '23 vendor pricing spreadsheets were shared with link-sharing enabled on the Marketing shared drive. Access restricted to procurement.',
  },
  {
    id: 'DTN-2034',
    title: 'Mailbox forwarding rule to external domain',
    severity: 'high',
    status: 'investigating',
    repositoryId: 'repo_ex_mail',
    repositoryName: 'Microsoft Exchange',
    classification: 'Exfiltration Risk',
    detectedAt: '2026-07-28T10:11:00Z',
    affectedAssets: 1,
    assignedTo: 'Sarah Johnson',
    description:
      'An auto-forwarding rule on a finance executive mailbox routes inbound mail to an external personal domain. Rule suspended pending review.',
  },
];

export const scans: Scan[] = [
  {
    id: 'SCAN-8821',
    name: 'Quarterly PII sweep — Finance',
    repositoryId: 'repo_sp_fin',
    repositoryName: 'SharePoint Finance',
    type: 'full',
    status: 'scanning',
    progress: 64,
    startedAt: '2026-07-30T11:02:00Z',
    lastRun: 'Today',
    duration: '00:42:18',
    estimatedCompletion: '18 mins',
    assetsScanned: 40793,
    sensitiveFound: 18620,
    triggeredBy: 'Michael Chen',
  },
  {
    id: 'SCAN-8820',
    name: 'Weekly classification — HR vault',
    repositoryId: 'repo_sp_hr',
    repositoryName: 'SharePoint HR',
    type: 'scheduled',
    status: 'completed',
    progress: 100,
    startedAt: '2026-07-29T08:14:00Z',
    lastRun: 'Today',
    duration: '01:12:04',
    estimatedCompletion: '—',
    assetsScanned: 48210,
    sensitiveFound: 12480,
    triggeredBy: 'Sarah Johnson',
  },
  {
    id: 'SCAN-8819',
    name: 'Access audit — Legal hold',
    repositoryId: 'repo_az_legal',
    repositoryName: 'Azure Blob Legal',
    type: 'incremental',
    status: 'completed',
    progress: 100,
    startedAt: '2026-07-29T22:17:00Z',
    lastRun: 'Today',
    duration: '00:38:51',
    estimatedCompletion: '—',
    assetsScanned: 42100,
    sensitiveFound: 21900,
    triggeredBy: 'Priya Nair',
  },
  {
    id: 'SCAN-8818',
    name: 'Deep discovery — Engineering S3',
    repositoryId: 'repo_s3_eng',
    repositoryName: 'AWS S3 Engineering',
    type: 'scheduled',
    status: 'scheduled',
    progress: 0,
    startedAt: '2026-08-01T02:00:00Z',
    lastRun: 'Tomorrow',
    duration: '—',
    estimatedCompletion: 'Scheduled',
    assetsScanned: 0,
    sensitiveFound: 0,
    triggeredBy: 'David Miller',
  },
  {
    id: 'SCAN-8817',
    name: 'Real-time monitor — CRM exports',
    repositoryId: 'repo_pg_crm',
    repositoryName: 'PostgreSQL CRM',
    type: 'incremental',
    status: 'paused',
    progress: 38,
    startedAt: '2026-07-29T14:08:00Z',
    lastRun: 'Today',
    duration: '00:22:10',
    estimatedCompletion: '—',
    assetsScanned: 7128,
    sensitiveFound: 3540,
    triggeredBy: 'David Miller',
  },
  {
    id: 'SCAN-8816',
    name: 'Mailbox exfiltration scan',
    repositoryId: 'repo_ex_mail',
    repositoryName: 'Microsoft Exchange',
    type: 'full',
    status: 'failed',
    progress: 0,
    startedAt: '2026-07-27T06:55:00Z',
    lastRun: 'Yesterday',
    duration: '00:03:42',
    estimatedCompletion: '—',
    assetsScanned: 0,
    sensitiveFound: 0,
    triggeredBy: 'Sarah Johnson',
  },
];

export const policies: Policy[] = [
  {
    id: 'POL-101',
    framework: 'PCI-DSS',
    category: 'Encryption',
    name: 'PCI-DSS Cardholder Data Encryption',
    type: 'encryption',
    status: 'enforced',
    severity: 'critical',
    repositories: 3,
    violations: 2,
    lastUpdated: '2026-07-26T10:00:00Z',
    owner: 'Michael Chen',
    description:
      'All cardholder data must be encrypted at rest with AES-256 and in transit with TLS 1.2+. Auto-quarantine applies to non-compliant assets.',
  },
  {
    id: 'POL-102',
    framework: 'GDPR',
    category: 'Data Residency',
    name: 'EU GDPR PII Residency Boundary',
    type: 'residency',
    status: 'enforced',
    severity: 'high',
    repositories: 5,
    violations: 0,
    lastUpdated: '2026-07-24T14:30:00Z',
    owner: 'Priya Nair',
    description:
      'Personal data of EU data subjects must reside exclusively within approved EU regions. Cross-region replication is blocked at the storage layer.',
  },
  {
    id: 'POL-103',
    framework: 'SOC 2',
    category: 'Access Governance',
    name: 'Least-Privilege Access to Sensitive Stores',
    type: 'access-governance',
    status: 'enforced',
    severity: 'high',
    repositories: 8,
    violations: 4,
    lastUpdated: '2026-07-28T09:15:00Z',
    owner: 'Sarah Johnson',
    description:
      'Access to repositories tagged Sensitive or higher requires just-in-time elevation approved by a data owner. Standing access is prohibited.',
  },
  {
    id: 'POL-104',
    framework: 'ISO 27001',
    category: 'Data Classification',
    name: 'Source Code & Build Artifact Classification',
    type: 'data-classification',
    status: 'enforced',
    severity: 'medium',
    repositories: 2,
    violations: 1,
    lastUpdated: '2026-07-21T16:45:00Z',
    owner: 'David Miller',
    description:
      'Engineering repositories must classify source code and build artifacts as Confidential and restrict public exposure paths.',
  },
  {
    id: 'POL-105',
    framework: 'ISO 27001',
    category: 'Retention',
    name: 'Legal Hold Retention — 7 Years',
    type: 'retention',
    status: 'enforced',
    severity: 'high',
    repositories: 2,
    violations: 0,
    lastUpdated: '2026-07-19T11:20:00Z',
    owner: 'Priya Nair',
    description:
      'Documents under legal hold must be retained for a minimum of 7 years with immutable storage and deletion protection enabled.',
  },
  {
    id: 'POL-106',
    framework: 'SOC 2',
    category: 'DLP',
    name: 'DLP — External Sharing of Financial Models',
    type: 'dlp',
    status: 'draft',
    severity: 'medium',
    repositories: 2,
    violations: 0,
    lastUpdated: '2026-07-29T17:05:00Z',
    owner: 'Sarah Johnson',
    description:
      'Draft policy to block external sharing of financial forecast models and sensitivity analyses outside approved partner domains.',
  },
  {
    id: 'POL-107',
    framework: 'SOC 2',
    category: 'DLP',
    name: 'Marketing Asset Public Exposure Rule',
    type: 'dlp',
    status: 'paused',
    severity: 'low',
    repositories: 1,
    violations: 3,
    lastUpdated: '2026-07-18T08:00:00Z',
    owner: 'David Miller',
    description:
      'Paused while Marketing restructures shared drive permissions. Intended to prevent public link-sharing of commercial-confidential assets.',
  },
];

export const activityFeed: ActivityEvent[] = [
  {
    id: 'act_1',
    type: 'detection',
    title: 'Critical detection opened on SharePoint Finance',
    description: 'DTN-2041 — Unencrypted PII in customer records export (1,840 assets).',
    actor: 'Aurora Engine',
    timestamp: '2026-07-30T09:42:00Z',
    severity: 'critical',
  },
  {
    id: 'act_2',
    type: 'scan',
    title: 'Quarterly PII sweep started',
    description: 'SCAN-8821 began scanning SharePoint Finance — 64% complete.',
    actor: 'Michael Chen',
    timestamp: '2026-07-30T11:02:00Z',
    severity: 'info',
  },
  {
    id: 'act_3',
    type: 'policy',
    title: 'DLP policy draft created',
    description: 'POL-106 — External sharing of financial models drafted for review.',
    actor: 'Sarah Johnson',
    timestamp: '2026-07-29T17:05:00Z',
    severity: 'info',
  },
  {
    id: 'act_4',
    type: 'remediation',
    title: 'Credential rotation completed',
    description: 'DTN-2037 remediated — stale CRM connection string rotated and invalidated.',
    actor: 'David Miller',
    timestamp: '2026-07-29T13:45:00Z',
    severity: 'info',
  },
  {
    id: 'act_5',
    type: 'access',
    title: 'Just-in-time elevation approved',
    description: 'Sarah Johnson granted 4-hour read access to Azure Blob Legal.',
    actor: 'Priya Nair',
    timestamp: '2026-07-29T22:20:00Z',
    severity: 'low',
  },
  {
    id: 'act_6',
    type: 'system',
    title: 'Exchange connector paused',
    description: 'Microsoft Exchange repository paused by administrator for reconfiguration.',
    actor: 'Sarah Johnson',
    timestamp: '2026-07-27T06:40:00Z',
    severity: 'info',
  },
];

export const notifications: Notification[] = [
  {
    id: 'n1',
    title: 'Critical detection: unencrypted PII',
    body: 'DTN-2041 on SharePoint Finance requires investigation.',
    timestamp: '2026-07-30T09:42:00Z',
    read: false,
    severity: 'critical',
    category: 'detection',
  },
  {
    id: 'n2',
    title: 'Scan progress: 64%',
    body: 'Quarterly PII sweep on SharePoint Finance is 64% complete.',
    timestamp: '2026-07-30T11:30:00Z',
    read: false,
    severity: 'info',
    category: 'scan',
  },
  {
    id: 'n3',
    title: 'Policy violation threshold reached',
    body: 'POL-103 recorded its 4th standing-access violation this week.',
    timestamp: '2026-07-29T18:50:00Z',
    read: false,
    severity: 'high',
    category: 'policy',
  },
  {
    id: 'n4',
    title: 'Repository connection restored',
    body: 'Azure Blob Legal connector re-established after token refresh.',
    timestamp: '2026-07-29T22:00:00Z',
    read: true,
    severity: 'info',
    category: 'system',
  },
];

export const overviewMetrics: MetricTrend[] = [
  {
    label: 'Sensitive Assets Discovered',
    value: 163420,
    change: 8.4,
    trend: [142000, 146500, 149800, 154200, 158100, 160900, 163420],
  },
  {
    label: 'Open Detections',
    value: 47,
    change: -12.5,
    trend: [62, 58, 55, 53, 51, 49, 47],
  },
  {
    label: 'Repositories Connected',
    value: 8,
    change: 14.3,
    trend: [6, 6, 7, 7, 7, 8, 8],
  },
  {
    label: 'Avg. Risk Score',
    value: 64.8,
    change: -3.1,
    trend: [71, 70, 69, 68, 67, 66, 64.8],
  },
];

export const classificationBreakdown: ClassificationBreakdown[] = [
  { label: 'PII', value: 64210, color: 'hsl(var(--primary))' },
  { label: 'PCI', value: 28940, color: 'hsl(var(--danger))' },
  { label: 'PHI', value: 18420, color: 'hsl(var(--warning))' },
  { label: 'Confidential', value: 31280, color: 'hsl(var(--chart-5))' },
  { label: 'Credentials', value: 4820, color: 'hsl(var(--success))' },
  { label: 'Public', value: 15150, color: 'hsl(var(--muted-foreground))' },
];

export const riskDistribution: RiskDistributionPoint[] = [
  { label: 'Mon', critical: 3, high: 7, medium: 12, low: 9 },
  { label: 'Tue', critical: 5, high: 6, medium: 14, low: 8 },
  { label: 'Wed', critical: 2, high: 9, medium: 11, low: 10 },
  { label: 'Thu', critical: 4, high: 5, medium: 13, low: 11 },
  { label: 'Fri', critical: 6, high: 8, medium: 10, low: 7 },
  { label: 'Sat', critical: 1, high: 3, medium: 6, low: 5 },
  { label: 'Sun', critical: 2, high: 4, medium: 8, low: 6 },
];

export const trendAnnotations: TrendAnnotation[] = [
  { label: 'SharePoint Migration', day: 'Tue' },
  { label: 'Quarterly Audit', day: 'Thu' },
  { label: 'Policy Update', day: 'Sat' },
];

export const morningBrief: MorningBrief = {
  greeting: 'Good Morning, Sarah',
  period: 'overnight',
  summaryPoints: [
    { text: 'Overnight scans completed successfully across 8 repositories.', tone: 'neutral' },
    { text: '12 new sensitive data findings were detected.', tone: 'neutral' },
    { text: '3 are considered Critical.', tone: 'critical' },
    { text: 'Risk exposure increased by 6%.', tone: 'warning' },
    { text: 'One SharePoint Finance folder became publicly accessible.', tone: 'critical' },
  ],
  estimatedReviewMinutes: 18,
  exposureDeltaPct: 6,
};

export const securityHealth: SecurityHealth = {
  score: 64.8,
  maxScore: 100,
  trend: 3.1,
  riskLevel: 'Moderate',
  explanation:
    'Your posture improved compared to yesterday, but three critical findings require immediate review.',
  metrics: [
    { label: 'Sensitive Files', value: 163420, change: 8.4 },
    { label: 'Open Detections', value: 47, change: -12.5, invertChangeColor: true },
    { label: 'Repositories Connected', value: 8, change: 14.3 },
    { label: 'Policies Active', value: 5, change: 0 },
  ],
};

export const workQueue: WorkQueueItem[] = [
  {
    id: 'wq_1',
    severity: 'critical',
    fileName: 'Payroll_2026.xlsx',
    reason: 'Publicly Shared',
    reasonTag: 'Restricted',
    repository: 'SharePoint Finance',
    detectedAt: '2026-07-31T07:42:00Z',
    classification: 'PII — Employee',
    affectedAssets: 1840,
    ctaLabel: 'Investigate',
  },
  {
    id: 'wq_2',
    severity: 'high',
    fileName: 'Customer_Master.csv',
    reason: 'Contains PAN + Aadhaar',
    reasonTag: 'PCI + PII',
    repository: 'Snowflake',
    detectedAt: '2026-07-31T06:15:00Z',
    classification: 'PCI — Cardholder',
    affectedAssets: 5400,
    ctaLabel: 'Review',
  },
  {
    id: 'wq_3',
    severity: 'high',
    fileName: 'Executive_M&A_Strategy.pdf',
    reason: 'External Share Link',
    reasonTag: 'Confidential',
    repository: 'Exchange',
    detectedAt: '2026-07-31T05:30:00Z',
    classification: 'Confidential — Strategic',
    affectedAssets: 1,
    ctaLabel: 'Review',
  },
  {
    id: 'wq_4',
    severity: 'medium',
    fileName: 'Engineering_Backup.sql',
    reason: 'Contains API Keys',
    reasonTag: 'Credential',
    repository: 'AWS S3',
    detectedAt: '2026-07-31T04:08:00Z',
    classification: 'Credential — Secret',
    affectedAssets: 12,
    ctaLabel: 'Review',
  },
];

export const aiRecommendations: AiRecommendation[] = [
  {
    id: 'rec_1',
    title: 'Restrict public access to Payroll_2026.xlsx',
    confidence: 98,
    impact: 'High',
    reason: 'Public link detected on a file classified as Restricted. Revoking the share link would reduce exposure by an estimated 14%.',
    ctaLabel: 'Review Recommendation',
    category: 'access',
  },
  {
    id: 'rec_2',
    title: 'Enable automatic scan for Finance SharePoint',
    confidence: 94,
    impact: 'Medium',
    reason: 'SharePoint Finance has no scheduled scan. Enabling a daily discovery window would catch exposure drift within hours.',
    ctaLabel: 'Schedule Scan',
    category: 'scan',
  },
  {
    id: 'rec_3',
    title: 'Enforce Least-Privilege policy on Azure Blob Legal',
    confidence: 89,
    impact: 'High',
    reason: '14 service principals retain standing access outside the legal team. Enforcing POL-103 would require just-in-time elevation instead.',
    ctaLabel: 'Review Recommendation',
    category: 'policy',
  },
];

export const briefActivity: BriefActivityItem[] = [
  {
    id: 'ba_1',
    actor: 'Michael Chen',
    initials: 'MC',
    color: '#0EA5E9',
    action: 'approved a policy',
    target: 'POL-103 Least-Privilege Access',
    timestamp: '2026-07-31T08:12:00Z',
    type: 'policy',
  },
  {
    id: 'ba_2',
    actor: 'Priya Nair',
    initials: 'PN',
    color: '#16A34A',
    action: 'reviewed',
    target: 'Customer_Master.csv',
    timestamp: '2026-07-31T07:40:00Z',
    type: 'review',
  },
  {
    id: 'ba_3',
    actor: 'Sarah Johnson',
    initials: 'SJ',
    color: '#4F46E5',
    action: 'dismissed one Medium finding',
    target: 'Engineering_Backup.sql',
    timestamp: '2026-07-31T06:55:00Z',
    type: 'dismiss',
  },
  {
    id: 'ba_4',
    actor: 'Aurora Engine',
    initials: 'AE',
    color: '#4F46E5',
    action: 'completed a scheduled scan',
    target: 'SharePoint HR vault',
    timestamp: '2026-07-31T05:00:00Z',
    type: 'scan',
  },
  {
    id: 'ba_5',
    actor: 'David Miller',
    initials: 'DM',
    color: '#D97706',
    action: 'connected a new repository',
    target: 'Azure Blob Legal',
    timestamp: '2026-07-31T03:24:00Z',
    type: 'connect',
  },
];

export const connectorSources: ConnectorSource[] = [
  { id: 'src_sharepoint', name: 'SharePoint', type: 'sharepoint', category: 'collaboration', description: 'Microsoft 365 SharePoint sites & document libraries' },
  { id: 'src_gdrive', name: 'Google Drive', type: 'google-drive', category: 'collaboration', description: 'Google Workspace shared drives & My Drive' },
  { id: 'src_onedrive', name: 'OneDrive', type: 'onedrive', category: 'collaboration', description: 'Microsoft OneDrive personal & business storage' },
  { id: 'src_s3', name: 'AWS S3', type: 's3', category: 'cloud-storage', description: 'Amazon S3 buckets & prefixes across all regions' },
  { id: 'src_azure', name: 'Azure Blob', type: 'azure-blob', category: 'cloud-storage', description: 'Azure Blob Storage containers & virtual directories' },
  { id: 'src_snowflake', name: 'Snowflake', type: 'snowflake', category: 'database', description: 'Snowflake warehouses, databases & schemas' },
  { id: 'src_postgres', name: 'PostgreSQL', type: 'postgresql', category: 'database', description: 'Managed or self-hosted PostgreSQL instances' },
  { id: 'src_mysql', name: 'MySQL', type: 'mysql', category: 'database', description: 'MySQL & Aurora MySQL databases' },
  { id: 'src_oracle', name: 'Oracle', type: 'oracle', category: 'database', description: 'Oracle Database schemas & tables' },
  { id: 'src_exchange', name: 'Exchange', type: 'exchange', category: 'collaboration', description: 'Microsoft Exchange Online mailboxes' },
  { id: 'src_github', name: 'GitHub', type: 'github', category: 'dev', description: 'GitHub repositories, branches & gists' },
  { id: 'src_box', name: 'Box', type: 'box', category: 'collaboration', description: 'Box enterprise content & folders' },
  { id: 'src_dropbox', name: 'Dropbox', type: 'dropbox', category: 'collaboration', description: 'Dropbox Business team spaces & folders' },
];

export const connectorActivity: ConnectorActivity[] = [
  { id: 'ca_1', action: 'connected', target: 'SharePoint Finance', timestamp: '2026-07-31T07:42:00Z', type: 'connect' },
  { id: 'ca_2', action: 'scan completed', target: 'Microsoft Exchange', timestamp: '2026-07-31T06:18:00Z', type: 'scan' },
  { id: 'ca_3', action: 'synced', target: 'Google Drive Marketing', timestamp: '2026-07-31T04:55:00Z', type: 'sync' },
  { id: 'ca_4', action: 'policy updated', target: 'Azure Blob Legal', timestamp: '2026-07-31T03:10:00Z', type: 'policy' },
  { id: 'ca_5', action: 'authenticated', target: 'Snowflake Analytics', timestamp: '2026-07-31T02:30:00Z', type: 'auth' },
];

export const dataSourcesRecommendation: DataSourcesRecommendation = {
  title: 'Increase scan frequency for SharePoint Finance',
  reason: '34% increase in newly discovered sensitive files over the past week. Daily scans would catch exposure drift within hours.',
  confidence: 97,
  repositoryName: 'SharePoint Finance',
  ctaLabel: 'Review Recommendation',
};

export const healthDistribution: HealthDistribution = {
  healthy: 6,
  needsAttention: 2,
  scanning: 1,
  disconnected: 0,
};

export const repositoryDetails: Record<string, RepositoryDetail> = {
  repo_sp_fin: {
    repositoryId: 'repo_sp_fin',
    connection: 'fair',
    connectionMethod: 'OAuth 2.0 · Microsoft Graph',
    createdAt: '2026-05-14T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Daily', time: '02:00 AM' },
    avgScanDuration: '1h 12m',
    classificationBreakdown: [
      { label: 'PII', value: 12840, color: 'hsl(var(--primary))' },
      { label: 'PCI', value: 8920, color: 'hsl(var(--danger))' },
      { label: 'Confidential', value: 5640, color: 'hsl(var(--chart-5))' },
      { label: 'Credentials', value: 510, color: 'hsl(var(--success))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Payroll_2026.xlsx', classification: 'PII — Employee', severity: 'critical' },
      { id: 'f2', name: 'Executive Documents', classification: 'Confidential — Strategic', severity: 'high' },
      { id: 'f3', name: 'Bank Statements Q3', classification: 'PCI — Cardholder', severity: 'high' },
      { id: 'f4', name: 'Vendor Contracts', classification: 'Confidential — Commercial', severity: 'medium' },
    ],
    activity: [
      { id: 'a1', action: 'Permission changed', target: 'Payroll folder', actor: 'Sarah Johnson', timestamp: '2026-07-31T08:14:00Z', type: 'permission' },
      { id: 'a2', action: 'Scan completed', target: 'Quarterly PII sweep', actor: 'Aurora Engine', timestamp: '2026-07-31T07:42:00Z', type: 'scan' },
      { id: 'a3', action: 'Repository synced', target: 'Document library', actor: 'Aurora Engine', timestamp: '2026-07-31T05:00:00Z', type: 'sync' },
      { id: 'a4', action: 'Policy updated', target: 'POL-101 Encryption', actor: 'Michael Chen', timestamp: '2026-07-30T16:20:00Z', type: 'policy' },
    ],
  },
  repo_sp_hr: {
    repositoryId: 'repo_sp_hr',
    connection: 'good',
    connectionMethod: 'OAuth 2.0 · Microsoft Graph',
    createdAt: '2026-04-22T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Daily', time: '02:00 AM' },
    avgScanDuration: '1h 12m',
    classificationBreakdown: [
      { label: 'PII', value: 9840, color: 'hsl(var(--primary))' },
      { label: 'PHI', value: 1840, color: 'hsl(var(--warning))' },
      { label: 'Confidential', value: 800, color: 'hsl(var(--chart-5))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Onboarding_2026', classification: 'PII — Identity', severity: 'high' },
      { id: 'f2', name: 'Benefits Enrollment', classification: 'PII — Employee', severity: 'medium' },
      { id: 'f3', name: 'Medical Records', classification: 'PHI — Health', severity: 'high' },
    ],
    activity: [
      { id: 'a1', action: 'Scan completed', target: 'Weekly classification', actor: 'Aurora Engine', timestamp: '2026-07-29T08:14:00Z', type: 'scan' },
      { id: 'a2', action: 'Repository synced', target: 'HR vault', actor: 'Aurora Engine', timestamp: '2026-07-29T06:00:00Z', type: 'sync' },
    ],
  },
  repo_s3_eng: {
    repositoryId: 'repo_s3_eng',
    connection: 'excellent',
    connectionMethod: 'IAM Role · Cross-account',
    createdAt: '2026-03-10T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Weekly', time: '02:00 AM' },
    avgScanDuration: '0h 38m',
    classificationBreakdown: [
      { label: 'Confidential', value: 7240, color: 'hsl(var(--chart-5))' },
      { label: 'Credentials', value: 1240, color: 'hsl(var(--success))' },
      { label: 'Public', value: 260, color: 'hsl(var(--muted-foreground))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Engineering_Backup.sql', classification: 'Credential — Secret', severity: 'medium' },
      { id: 'f2', name: 'Release Artifacts', classification: 'Confidential — Source', severity: 'medium' },
      { id: 'f3', name: 'Config Manifests', classification: 'Credential — Secret', severity: 'low' },
    ],
    activity: [
      { id: 'a1', action: 'Scan scheduled', target: 'Deep discovery', actor: 'David Miller', timestamp: '2026-07-30T14:00:00Z', type: 'scan' },
      { id: 'a2', action: 'Repository synced', target: 'Engineering bucket', actor: 'Aurora Engine', timestamp: '2026-07-28T03:41:00Z', type: 'sync' },
    ],
  },
  repo_sf_an: {
    repositoryId: 'repo_sf_an',
    connection: 'good',
    connectionMethod: 'Service Account · Key-pair auth',
    createdAt: '2026-06-01T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Daily', time: '02:00 AM' },
    avgScanDuration: '0h 22m',
    classificationBreakdown: [
      { label: 'PII', value: 12630, color: 'hsl(var(--primary))' },
      { label: 'PCI', value: 3000, color: 'hsl(var(--danger))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Customer_Master view', classification: 'PII — Identity', severity: 'low' },
      { id: 'f2', name: 'Revenue Forecast schema', classification: 'Confidential — Strategic', severity: 'medium' },
    ],
    activity: [
      { id: 'a1', action: 'Authenticated', target: 'Service account', actor: 'Aurora Engine', timestamp: '2026-07-31T02:30:00Z', type: 'auth' },
      { id: 'a2', action: 'Scan completed', target: 'Daily discovery', actor: 'Aurora Engine', timestamp: '2026-07-29T19:22:00Z', type: 'scan' },
    ],
  },
  repo_pg_crm: {
    repositoryId: 'repo_pg_crm',
    connection: 'good',
    connectionMethod: 'SSL · Connection string',
    createdAt: '2026-05-28T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Daily', time: '02:00 AM' },
    avgScanDuration: '0h 18m',
    classificationBreakdown: [
      { label: 'PII', value: 7420, color: 'hsl(var(--primary))' },
      { label: 'Confidential', value: 2000, color: 'hsl(var(--chart-5))' },
    ],
    topFindings: [
      { id: 'f1', name: 'customers table', classification: 'PII — Identity', severity: 'medium' },
      { id: 'f2', name: 'connection_config', classification: 'Credential — Secret', severity: 'medium' },
    ],
    activity: [
      { id: 'a1', action: 'Credential rotated', target: 'Connection string', actor: 'David Miller', timestamp: '2026-07-29T13:45:00Z', type: 'permission' },
      { id: 'a2', action: 'Scan completed', target: 'Real-time monitor', actor: 'Aurora Engine', timestamp: '2026-07-29T14:08:00Z', type: 'scan' },
    ],
  },
  repo_ex_mail: {
    repositoryId: 'repo_ex_mail',
    connection: 'poor',
    connectionMethod: 'OAuth 2.0 · Microsoft Graph',
    createdAt: '2026-02-15T09:00:00Z',
    nextScan: '—',
    scanSchedule: { frequency: 'Paused', time: '—' },
    avgScanDuration: '0h 03m',
    classificationBreakdown: [
      { label: 'PII', value: 51200, color: 'hsl(var(--primary))' },
      { label: 'Confidential', value: 13010, color: 'hsl(var(--chart-5))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Finance Mailbox', classification: 'Exfiltration Risk', severity: 'high' },
      { id: 'f2', name: 'Executive Inbox', classification: 'Confidential — Strategic', severity: 'high' },
    ],
    activity: [
      { id: 'a1', action: 'Connector paused', target: 'Mailbox connector', actor: 'Sarah Johnson', timestamp: '2026-07-27T06:40:00Z', type: 'permission' },
      { id: 'a2', action: 'Scan failed', target: 'Mailbox exfiltration', actor: 'Aurora Engine', timestamp: '2026-07-27T06:55:00Z', type: 'scan' },
    ],
  },
  repo_az_legal: {
    repositoryId: 'repo_az_legal',
    connection: 'fair',
    connectionMethod: 'SAS Token · Shared Access Signature',
    createdAt: '2026-06-18T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Daily', time: '02:00 AM' },
    avgScanDuration: '0h 39m',
    classificationBreakdown: [
      { label: 'Confidential', value: 15900, color: 'hsl(var(--chart-5))' },
      { label: 'PII', value: 6000, color: 'hsl(var(--primary))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Legal Hold Container', classification: 'Privileged — Legal', severity: 'high' },
      { id: 'f2', name: 'Litigation Files', classification: 'Confidential — Legal', severity: 'medium' },
    ],
    activity: [
      { id: 'a1', action: 'Access audit completed', target: 'Legal hold', actor: 'Aurora Engine', timestamp: '2026-07-29T22:17:00Z', type: 'scan' },
      { id: 'a2', action: 'Connected', target: 'Azure Blob Legal', actor: 'David Miller', timestamp: '2026-07-31T03:24:00Z', type: 'connect' },
    ],
  },
  repo_gd_mktg: {
    repositoryId: 'repo_gd_mktg',
    connection: 'excellent',
    connectionMethod: 'OAuth 2.0 · Google Workspace',
    createdAt: '2026-07-01T09:00:00Z',
    nextScan: '2026-08-01T02:00:00Z',
    scanSchedule: { frequency: 'Weekly', time: '02:00 AM' },
    avgScanDuration: '0h 14m',
    classificationBreakdown: [
      { label: 'Public', value: 16800, color: 'hsl(var(--muted-foreground))' },
      { label: 'Confidential', value: 2140, color: 'hsl(var(--chart-5))' },
    ],
    topFindings: [
      { id: 'f1', name: 'Vendor Pricing', classification: 'Confidential — Commercial', severity: 'low' },
      { id: 'f2', name: 'Campaign Assets', classification: 'Public', severity: 'low' },
    ],
    activity: [
      { id: 'a1', action: 'Synced', target: 'Marketing shared drive', actor: 'Aurora Engine', timestamp: '2026-07-31T04:55:00Z', type: 'sync' },
      { id: 'a2', action: 'Scan completed', target: 'Weekly discovery', actor: 'Aurora Engine', timestamp: '2026-07-28T16:30:00Z', type: 'scan' },
    ],
  },
};

export function healthStatusForRepository(repo: Repository): RepositoryHealthStatus {
  if (repo.status === 'scanning') return 'scanning';
  if (repo.status === 'paused') return 'needs-attention';
  if (repo.riskScore >= 80) return 'needs-attention';
  const daysSinceScan = (Date.now() - new Date(repo.lastScanned).getTime()) / 86_400_000;
  if (daysSinceScan > 3) return 'needs-scan';
  return 'healthy';
}
